name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    environment: demo
    runs-on: ubuntu-latest
    steps:
      - name: Show env
        run: env|sort
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: ./scripts/generate_content_files.sh
      - name: Hugo build
        uses: jakejarvis/hugo-build-action@master
        with:
          args: --source=hugo
      - run: ls -la ./hugo/public
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: the-youtube-synopsis
          source_dir: 'hugo/public'
          destination_dir: ''