name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  "build and deploy":
    runs-on: ubuntu-latest
    steps:
      - name: Show env
        run: env|sort
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hugo build
        uses: jakejarvis/hugo-build-action@master
        
